version: '3.8'

services:
  db:
    image: postgres:16
    container_name: wms_postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d

volumes:
  pgdata: